# <u> Use only those concepts which have been taught till now </u>

In [1]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [ ]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
new=random_integers[:5,2:4]
print(new)
average=np.sum(new)/np.size(new)
print(average)

[[202553 140037]
 [261540 481981]
 [110795 394863]
 [408830 485118]
 [265455 109413]]
286058.5


#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points
np.random.seed(20)
new=np.random.randint(5,20,(10,2))
print(new)

[[ 8 15]
 [17 15]
 [14  9]
 [16 11]
 [12  7]
 [ 5 11]
 [13 10]
 [15 15]
 [16  8]
 [ 5 18]]


In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
#eu=np.array([])
#np.resize(eu,(1,10))
list_1=list()
for i in np.arange(9):
  j=0
  x=(abs((new[i,j]-new[i+1,j])**2)+abs((new[i,j+1]-new[i+1,j+1])**2))**(1/2)
  list_1.append(x)
  
eu=np.array(list_1,dtype=int)
print(eu)

list_2=list()
for y in np.arange(9):
  a=0
  z=(abs(new[y,a]-new[y+1,a])+abs(new[y,a+1]-new[y+1,a+1]))
  list_2.append(z)

mh=np.array(list_2)  
print(mh)





[ 9  6  2  5  8  8  5  7 14]
[ 9  9  4  8 11  9  7  8 21]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here
min_eu=np.min(eu)
min_mh=np.min(mh)
print(min_eu)
print(min_mh)


2
4


# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..
np.random.seed(21)
con=np.random.randint(5,39,(10,10))
print(con)
list_result=list()

def coun():
  for q in np.arange(8):
    j=0
    for i in np.arange(8):
      value=con[q:q+3,i:j+3]
      j+=1
      list_result.append(value)
    
  np.array(list_result)
  print(list_result)


[[14 20  9 15 13 25 25 17 10 23]
 [11 10 21 32 38 17 23 20 11 25]
 [31 33 14 21  5 10 10  9 17 35]
 [35 17 30 37 31 37 30 20  7 12]
 [38 13 35 29 30  5 30 33 19 10]
 [23 37  9 37 21  6  6 32 38 37]
 [36  7 27 15 34 30 22  8  6  6]
 [20 38 38 16 16 18 27 22 14 34]
 [ 8 35 33 29  6  6 33 21 30 15]
 [14  9 33 21  5 35 19  6 19  6]]


In [ ]:
coun()

[array([[14, 20,  9],
       [11, 10, 21],
       [31, 33, 14]]), array([[20,  9, 15],
       [10, 21, 32],
       [33, 14, 21]]), array([[ 9, 15, 13],
       [21, 32, 38],
       [14, 21,  5]]), array([[15, 13, 25],
       [32, 38, 17],
       [21,  5, 10]]), array([[13, 25, 25],
       [38, 17, 23],
       [ 5, 10, 10]]), array([[25, 25, 17],
       [17, 23, 20],
       [10, 10,  9]]), array([[25, 17, 10],
       [23, 20, 11],
       [10,  9, 17]]), array([[17, 10, 23],
       [20, 11, 25],
       [ 9, 17, 35]]), array([[11, 10, 21],
       [31, 33, 14],
       [35, 17, 30]]), array([[10, 21, 32],
       [33, 14, 21],
       [17, 30, 37]]), array([[21, 32, 38],
       [14, 21,  5],
       [30, 37, 31]]), array([[32, 38, 17],
       [21,  5, 10],
       [37, 31, 37]]), array([[38, 17, 23],
       [ 5, 10, 10],
       [31, 37, 30]]), array([[17, 23, 20],
       [10, 10,  9],
       [37, 30, 20]]), array([[23, 20, 11],
       [10,  9, 17],
       [30, 20,  7]]), array([[20, 11, 25],
   

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [41]:
# Your function below
def near(n=67):
  np.random.seed(21)
  arr=np.random.randint(10,500,size=15,dtype=int)
  print(arr)
  empty_1=np.array([])
  empty_2=np.array([])
  for i in arr:
    if i<n:
      empty_1=np.append(empty_1,i)
    elif i>n:
      empty_2=np.append(empty_2,i)
    else:
      print(i)
      break

  maximum=np.max(empty_1)
  minimum=np.min(empty_2)
  if abs(n-maximum)>abs(n-minimum):
    print(minimun)
  else:
    print(maximum)  


  
  

In [43]:
near(200)

[467 217 322 270  58 378 130 429 198 108 251 212 338 120 457]
198.0
